[project]
name = "airfoil-calcurator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "openmdao>=3.41.0",
    "optuna>=4.5.0",
    "pandas>=2.3.3",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
]
